#pragma once

#include "offboard_core_pkg/tasks/arm_task.hpp"
#include "offboard_core_pkg/tasks/align_down_task.hpp"
#include "offboard_core_pkg/tasks/hover_task.hpp"
#include "offboard_core_pkg/tasks/land_task.hpp"
#include "offboard_core_pkg/tasks/presetpoint_task.hpp"
#include "offboard_core_pkg/tasks/set_offboard_task.hpp"
#include "offboard_core_pkg/tasks/takeoff_task.hpp"
#include "offboard_core_pkg/tasks/goto_task.hpp"
#include "offboard_core_pkg/tasks/snake_grid_task.hpp"
#include "offboard_core_pkg/tasks/ego_goto_task.hpp"
#include "offboard_core_pkg/tasks/ego_vel_follow_task.hpp"
#include "offboard_core_pkg/tasks/door_navigation_task.hpp"
#include "offboard_core_pkg/tasks/snake_ego_avoid_task.hpp"
#include "offboard_core_pkg/tasks/align_drop_snake_ego_task.hpp"
